In [146]:
import pandas as pd
import numpy as np

In [147]:
df_248 = pd.read_excel("/Users/friana/Medical Adherence/data/MEPS/h248a.xlsx")

In [148]:
pd.set_option('display.max_columns', None)
df_248.head()

,DUID,PID,DUPERSID,DRUGIDX,RXRECIDX,LINKIDX,PANEL,PURCHRD,RXBEGMM,RXBEGYRX,RXNAME,RXDRGNAM,RXNDC,RXQUANTY,RXFORM,RXFRMUNT,RXSTRENG,RXSTRUNT,RXDAYSUP,PHARTP1,PHARTP2,PHARTP3,PHARTP4,PHARTP5,PHARTP6,RXFLG,IMPFLAG,PCIMPFLG,DIABEQUIP,INPCFLG,TC1,TC1S1,TC1S1_1,TC1S1_2,TC1S2,TC1S2_1,TC1S3,TC1S3_1,TC2,TC2S1,TC2S1_1,TC2S1_2,TC2S2,TC3,TC3S1,TC3S1_1,RXSF23X,RXMR23X,RXMD23X,RXPV23X,RXVA23X,RXTR23X,RXOF23X,RXSL23X,RXWC23X,RXOT23X,RXXP23X,PERWT23F,VARSTR,VARPSU
0,2790002,101,2790002101,2790002101002,2790002101002303001,2790002101002303,27,3,-1,-1,BD PEN NEEDL,-15,8290320550,100.0,MISC,EA,-15,-15,-8,4,-1,-1,-1,-1,-1,1,4,2,1,1,-15,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,13.00,0.0,0.0,41.78,0.0,0.0,0.0,0.0,0.0,0.0,54.78,11664.426815,2019,1
1,2790002,101,2790002101,2790002101006,2790002101006403001,2790002101006403,27,4,5,2023,PREDNISONE,PREDNISONE,591544210,40.0,TABS,EA,10,MG,16,4,4,-1,-1,-1,-1,1,2,1,2,1,97,98,301,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,7.20,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,7.20,11664.426815,2019,1
2,2790002,101,2790002101,2790002101007,2790002101007403001,2790002101007403,27,4,7,2023,PREDNISONE,PREDNISONE,70954006020,10.0,TABS,EA,20,MG,5,4,4,-1,-1,-1,-1,1,5,1,2,1,97,98,301,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2.39,0.0,0.0,10.93,0.0,0.0,0.0,0.0,0.0,0.0,13.32,11664.426815,2019,1
3,2790002,101,2790002101,2790002101008,2790002101008403001,2790002101008403,27,4,-15,2020,METFORMIN,METFORMIN,70010006305,60.0,TABS,EA,500,MG,30,4,4,-1,-1,-1,-1,1,2,1,2,1,358,99,214,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,6.22,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,6.22,11664.426815,2019,1
4,2790002,101,2790002101,2790002101008,2790002101008403002,2790002101008403,27,4,-15,2020,METFORMIN,METFORMIN,378718505,60.0,TABS,EA,500,MG,30,4,4,-1,-1,-1,-1,1,2,1,2,1,358,99,214,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,6.22,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,6.22,11664.426815,2019,1

In [149]:
clean_df = df_248[["DUPERSID","DRUGIDX","LINKIDX","RXRECIDX","RXDAYSUP","RXNAME","RXBEGYRX","RXNDC","RXXP23X","RXSF23X","TC1","TC1S1"]]


clean_df.to_excel("/Users/friana/Medical Adherence/data/MEPS/h248a_clean.xlsx")
pd.set_option('display.max_columns', None)
clean_df.head()

,DUPERSID,DRUGIDX,LINKIDX,RXRECIDX,RXDAYSUP,RXNAME,RXBEGYRX,RXNDC,RXXP23X,RXSF23X,TC1,TC1S1
0,2790002101,2790002101002,2790002101002303,2790002101002303001,-8,BD PEN NEEDL,-1,8290320550,54.78,13.00,-15,-1
1,2790002101,2790002101006,2790002101006403,2790002101006403001,16,PREDNISONE,2023,591544210,7.20,7.20,97,98
2,2790002101,2790002101007,2790002101007403,2790002101007403001,5,PREDNISONE,2023,70954006020,13.32,2.39,97,98
3,2790002101,2790002101008,2790002101008403,2790002101008403001,30,METFORMIN,2020,70010006305,6.22,6.22,358,99
4,2790002101,2790002101008,2790002101008403,2790002101008403002,30,METFORMIN,2020,378718505,6.22,6.22,358,99

In [150]:
clean_df = clean_df[clean_df["RXDAYSUP"]>0]
clean_df.head()

,DUPERSID,DRUGIDX,LINKIDX,RXRECIDX,RXDAYSUP,RXNAME,RXBEGYRX,RXNDC,RXXP23X,RXSF23X,TC1,TC1S1
1,2790002101,2790002101006,2790002101006403,2790002101006403001,16,PREDNISONE,2023,591544210,7.20,7.20,97,98
2,2790002101,2790002101007,2790002101007403,2790002101007403001,5,PREDNISONE,2023,70954006020,13.32,2.39,97,98
3,2790002101,2790002101008,2790002101008403,2790002101008403001,30,METFORMIN,2020,70010006305,6.22,6.22,358,99
4,2790002101,2790002101008,2790002101008403,2790002101008403002,30,METFORMIN,2020,378718505,6.22,6.22,358,99
5,2790002101,2790002101008,2790002101008503,2790002101008503001,30,METFORMIN,2020,68645058259,4.00,4.00,358,99

In [151]:
clean_df = clean_df[clean_df["RXDAYSUP"]<990]
clean_df.shape
#clean_df.head()

(139681, 12)

In [152]:
clean_df["RXBEGYRX"].describe()

count    139681.000000
mean       1644.914197
std         783.855548
min         -15.000000
25%        2003.000000
50%        2018.000000
75%        2022.000000
max        2024.000000
Name: RXBEGYRX, dtype: float64

In [153]:
new_df_invalid = clean_df[clean_df["RXBEGYRX"]<0]
new_df_invalid.shape

(25663, 12)

In [154]:
clean_df = clean_df[clean_df["RXBEGYRX"]>0]
clean_df.shape

(114018, 12)

In [155]:
clean_df.columns.tolist()

['DUPERSID',
 'DRUGIDX',
 'LINKIDX',
 'RXRECIDX',
 'RXDAYSUP',
 'RXNAME',
 'RXBEGYRX',
 'RXNDC',
 'RXXP23X',
 'RXSF23X',
 'TC1',
 'TC1S1']

In [156]:
grouped_clean_df = clean_df.groupby(["DUPERSID","DRUGIDX"]).agg(
    RXDAYSUP = ("RXDAYSUP", "sum"),
    RXXP23X = ("RXXP23X", "mean"),
    RXSF23X = ("RXSF23X", "mean"),
    RXNAME = ("RXNAME", "first"),
    RXNDC = ("RXNDC", "first"),
    RXBEGYRX = ("RXBEGYRX", "first"),
    RXRECIDX = ("RXRECIDX", "first"),
    TC1 = ("TC1", "first"),
    TC1S1 = ("TC1S1", "first"),
    LINKIDX = ("LINKIDX", "first")

   
)

grouped_clean_df.head()

                          RXDAYSUP  RXXP23X  RXSF23X       RXNAME  \
DUPERSID   DRUGIDX
2790002101 2790002101006        16    7.200    7.200   PREDNISONE
           2790002101007         5   13.320    2.390   PREDNISONE
           2790002101008       150    4.888    3.288    METFORMIN
           2790002101009        84   21.090    0.000    VITAMIN D
2790011101 2790011101001       270   10.000   10.000  PRAVASTATIN

                                RXNDC  RXBEGYRX             RXRECIDX  TC1  \
DUPERSID   DRUGIDX
2790002101 2790002101006    591544210      2023  2790002101006403001   97
           2790002101007  70954006020      2023  2790002101007403001   97
           2790002101008  70010006305      2020  2790002101008403001  358
           2790002101009  42806054701      2023  2790002101009503001  115
2790011101 2790011101001     93720298      2021  2790011101001303001  358

                          TC1S1           LINKIDX
DUPERSID   DRUGIDX
2790002101 2790002101006     98  2790002101006403
           2790002101007     98  2790002101007403
           2790002101008     99  2790002101008403
           2790002101009    119  2790002101009503
2790011101 2790011101001     19  2790011101001303

In [157]:
grouped_clean_df["total_days_supply"] = np.where(grouped_clean_df["RXBEGYRX"] <=2023, 365,0).astype(int)

grouped_clean_df.shape

grouped_clean_df["total_days_supply"].describe()
#grouped_clean_df.to_excel("/Users/friana/Medical Adherence/data/MEPS/h248a_grouped.xlsx")

count    35580.000000
mean       364.189573
std         17.180146
min          0.000000
25%        365.000000
50%        365.000000
75%        365.000000
max        365.000000
Name: total_days_supply, dtype: float64

In [158]:
grouped_clean_df = grouped_clean_df[grouped_clean_df["total_days_supply"]>0]

In [159]:
grouped_clean_df["meps_adherence_ratio"] = grouped_clean_df["RXDAYSUP"]/grouped_clean_df["total_days_supply"] *100
grouped_clean_df.head()

                          RXDAYSUP  RXXP23X  RXSF23X       RXNAME  \
DUPERSID   DRUGIDX
2790002101 2790002101006        16    7.200    7.200   PREDNISONE
           2790002101007         5   13.320    2.390   PREDNISONE
           2790002101008       150    4.888    3.288    METFORMIN
           2790002101009        84   21.090    0.000    VITAMIN D
2790011101 2790011101001       270   10.000   10.000  PRAVASTATIN

                                RXNDC  RXBEGYRX             RXRECIDX  TC1  \
DUPERSID   DRUGIDX
2790002101 2790002101006    591544210      2023  2790002101006403001   97
           2790002101007  70954006020      2023  2790002101007403001   97
           2790002101008  70010006305      2020  2790002101008403001  358
           2790002101009  42806054701      2023  2790002101009503001  115
2790011101 2790011101001     93720298      2021  2790011101001303001  358

                          TC1S1           LINKIDX  total_days_supply  \
DUPERSID   DRUGIDX
2790002101 2790002101006     98  2790002101006403                365
           2790002101007     98  2790002101007403                365
           2790002101008     99  2790002101008403                365
           2790002101009    119  2790002101009503                365
2790011101 2790011101001     19  2790011101001303                365

                          meps_adherence_ratio
DUPERSID   DRUGIDX
2790002101 2790002101006              4.383562
           2790002101007              1.369863
           2790002101008             41.095890
           2790002101009             23.013699
2790011101 2790011101001             73.972603

In [160]:
grouped_clean_df["RXDAYSUP"].describe()
grouped_clean_df.to_excel("/Users/friana/Medical Adherence/data/MEPS/h248a_Ratio.xlsx")
#grouped_clean_df = pd.read_excel("/Users/friana/Medical Adherence/data/MEPS/h248a_Ratio.xlsx")

In [161]:
grouped_clean_df.head()

                          RXDAYSUP  RXXP23X  RXSF23X       RXNAME  \
DUPERSID   DRUGIDX
2790002101 2790002101006        16    7.200    7.200   PREDNISONE
           2790002101007         5   13.320    2.390   PREDNISONE
           2790002101008       150    4.888    3.288    METFORMIN
           2790002101009        84   21.090    0.000    VITAMIN D
2790011101 2790011101001       270   10.000   10.000  PRAVASTATIN

                                RXNDC  RXBEGYRX             RXRECIDX  TC1  \
DUPERSID   DRUGIDX
2790002101 2790002101006    591544210      2023  2790002101006403001   97
           2790002101007  70954006020      2023  2790002101007403001   97
           2790002101008  70010006305      2020  2790002101008403001  358
           2790002101009  42806054701      2023  2790002101009503001  115
2790011101 2790011101001     93720298      2021  2790011101001303001  358

                          TC1S1           LINKIDX  total_days_supply  \
DUPERSID   DRUGIDX
2790002101 2790002101006     98  2790002101006403                365
           2790002101007     98  2790002101007403                365
           2790002101008     99  2790002101008403                365
           2790002101009    119  2790002101009503                365
2790011101 2790011101001     19  2790011101001303                365

                          meps_adherence_ratio
DUPERSID   DRUGIDX
2790002101 2790002101006              4.383562
           2790002101007              1.369863
           2790002101008             41.095890
           2790002101009             23.013699
2790011101 2790011101001             73.972603

In [162]:
by_drug_class = (
    grouped_clean_df.groupby(["TC1", "TC1S1"], as_index=False)
    .agg(meps_adherence_ratio=("meps_adherence_ratio", "mean"))
    .sort_values("meps_adherence_ratio", ascending=False)
)

top_10_highest = by_drug_class.head(10)
top_10_lowest = by_drug_class.tail(10).sort_values("meps_adherence_ratio", ascending=True)

print("Top 10 highest mean adherence:")
display(top_10_highest)

print("Top 10 lowest mean adherence:")
display(top_10_lowest)

Top 10 highest mean adherence:

     TC1  TC1S1  meps_adherence_ratio
20    40     42             74.618696
28    40     51             73.972603
31    40     55             71.518355
25    40     47             70.174942
14    20     23             69.895246
63    97    103             69.685220
105  358     19             69.666603
26    40     48             68.943028
32    40     56             68.796823
64    97    288             67.558421

Top 10 lowest mean adherence:

    TC1  TC1S1  meps_adherence_ratio
73  113    266              1.538462
12    1    240              2.669477
2     1      2              2.669640
9     1     14              3.141128
7     1     11              3.160132
8     1     13              3.248117
81  122    124              3.706194
6     1      9              3.959487
86  122    132              3.988322
93  133    148              4.088514

In [163]:
top_10_highest.to_excel("/Users/friana/Medical Adherence/data/MEPS/h248a_high.xlsx")
top_10_lowest.to_excel("/Users/friana/Medical Adherence/data/MEPS/h248a_low.xlsx")

In [164]:
chronic_df = pd.read_excel("/Users/friana/Medical Adherence/data/MEPS/is_chronic.xlsx")
chronic_df.head()

,ICD10CDX,ICD10CDX_LABEL,UNWEIGHTED,WEIGHTED_BY_perwt23f,is_chronic
0,-15,CANNOT BE COMPUTED,7557,1.237057e+08,0
1,A08,VIRAL AND OTHER SPECIFIED INTESTINAL INFECTIONS,99,1.921659e+06,0
2,A49,BACTERIAL INFECTION OF UNSPECIFIED SITE,91,1.711817e+06,0
3,B00,HERPESVIRAL [HERPES SIMPLEX] INFECTIONS,91,1.370652e+06,0
4,B02,ZOSTER [HERPES ZOSTER],76,1.294114e+06,0

In [165]:
connecting_df = pd.read_excel("/Users/friana/Medical Adherence/data/MEPS/h248if1.xlsx")
connecting_df.head()

,DUPERSID,CONDIDX,EVNTIDX,CLNKIDX,EVENTYPE,PANEL
0,2790002101,2790002101001,2790002101001200,27900021010012790002101001201,1,27
1,2790002101,2790002101001,2790002101001801,27900021010012790002101001801,1,27
2,2790002101,2790002101001,2790002101002303,27900021010012790002101002303,8,27
3,2790002101,2790002101004,2790002101001201,27900021010042790002101001201,1,27
4,2790002101,2790002101005,2790002101001301,27900021010052790002101001301,1,27

In [166]:
condition_df = pd.read_excel("/Users/friana/Medical Adherence/data/MEPS/h249.xlsx")
condition_df.head()

,DUID,PID,DUPERSID,CONDN,CONDIDX,PANEL,CONDRN,AGEDIAG,CRND1,CRND2,CRND3,CRND4,CRND5,INJURY,ACCDNWRK,ICD10CDX,CCSR1X,CCSR2X,CCSR3X,CCSR4X,HHCOND,IPCOND,OPCOND,OBCOND,ERCOND,RXCOND,PERWT23F,VARSTR,VARPSU
0,2790002,101,2790002101,1,2790002101001,27,1,55,-1,-1,1,1,1,2,-1,E11,END002,END005,-1,-1,2,2,2,1,2,1,11664.426815,2019,1
1,2790002,101,2790002101,4,2790002101004,27,3,-1,-1,-1,1,1,0,2,-1,R03,SYM012,-1,-1,-1,2,2,2,1,2,2,11664.426815,2019,1
2,2790002,101,2790002101,5,2790002101005,27,4,-1,-1,-1,0,1,0,2,-1,L30,INJ031,SKN007,-1,-1,2,2,1,1,2,1,11664.426815,2019,1
3,2790002,101,2790002101,6,2790002101006,27,4,-1,-1,-1,0,1,1,2,-1,E11,END002,END005,-1,-1,2,2,2,2,2,1,11664.426815,2019,1
4,2790002,101,2790002101,8,2790002101008,27,5,-1,-1,-1,0,0,1,2,-1,E55,END007,-1,-1,-1,2,2,2,2,2,1,11664.426815,2019,1

In [167]:
condition_df = condition_df[["DUPERSID","CONDIDX","ICD10CDX","AGEDIAG"]]
condition_df.head()

     DUPERSID        CONDIDX ICD10CDX  AGEDIAG
0  2790002101  2790002101001      E11       55
1  2790002101  2790002101004      R03       -1
2  2790002101  2790002101005      L30       -1
3  2790002101  2790002101006      E11       -1
4  2790002101  2790002101008      E55       -1

In [168]:
condition_df = pd.merge(condition_df,chronic_df, on="ICD10CDX", how="left")
condition_df.head()

,DUPERSID,CONDIDX,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,UNWEIGHTED,WEIGHTED_BY_perwt23f,is_chronic
0,2790002101,2790002101001,E11,55,TYPE 2 DIABETES MELLITUS,2009,28805030.81,1
1,2790002101,2790002101004,R03,-1,"ABNORMAL BLOOD-PRESSURE READING, WITHOUT DIAGN...",56,868076.60,0
2,2790002101,2790002101005,L30,-1,OTHER AND UNSPECIFIED DERMATITIS,210,3803279.08,0
3,2790002101,2790002101006,E11,-1,TYPE 2 DIABETES MELLITUS,2009,28805030.81,1
4,2790002101,2790002101008,E55,-1,VITAMIN D DEFICIENCY,294,4622089.29,0

In [169]:
condition_df = condition_df.drop(columns=["UNWEIGHTED","WEIGHTED_BY_perwt23f"])
condition_df.head()

,DUPERSID,CONDIDX,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
0,2790002101,2790002101001,E11,55,TYPE 2 DIABETES MELLITUS,1
1,2790002101,2790002101004,R03,-1,"ABNORMAL BLOOD-PRESSURE READING, WITHOUT DIAGN...",0
2,2790002101,2790002101005,L30,-1,OTHER AND UNSPECIFIED DERMATITIS,0
3,2790002101,2790002101006,E11,-1,TYPE 2 DIABETES MELLITUS,1
4,2790002101,2790002101008,E55,-1,VITAMIN D DEFICIENCY,0

In [170]:
condition_df = condition_df[condition_df["is_chronic"]>0.0]
condition_df.head()

,DUPERSID,CONDIDX,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
0,2790002101,2790002101001,E11,55,TYPE 2 DIABETES MELLITUS,1
3,2790002101,2790002101006,E11,-1,TYPE 2 DIABETES MELLITUS,1
5,2790006101,2790006101002,E78,70,DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...,1
6,2790006101,2790006101003,E11,71,TYPE 2 DIABETES MELLITUS,1
7,2790006101,2790006101004,C50,-1,MALIGNANT NEOPLASM OF BREAST,1

In [171]:
condition_df = pd.merge(connecting_df, condition_df, on="CONDIDX", how="left")
condition_df.head()

,DUPERSID_x,CONDIDX,EVNTIDX,CLNKIDX,EVENTYPE,PANEL,DUPERSID_y,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
0,2790002101,2790002101001,2790002101001200,27900021010012790002101001201,1,27,2.790002e+09,E11,55.0,TYPE 2 DIABETES MELLITUS,1.0
1,2790002101,2790002101001,2790002101001801,27900021010012790002101001801,1,27,2.790002e+09,E11,55.0,TYPE 2 DIABETES MELLITUS,1.0
2,2790002101,2790002101001,2790002101002303,27900021010012790002101002303,8,27,2.790002e+09,E11,55.0,TYPE 2 DIABETES MELLITUS,1.0
3,2790002101,2790002101004,2790002101001201,27900021010042790002101001201,1,27,NaN,NaN,NaN,NaN,NaN
4,2790002101,2790002101005,2790002101001301,27900021010052790002101001301,1,27,NaN,NaN,NaN,NaN,NaN

In [172]:
condition_df = condition_df.drop(columns=["DUPERSID_y","PANEL"])
condition_df = condition_df.rename(columns={"DUPERSID_x":"DUPERSID"})
condition_df = condition_df[condition_df["EVENTYPE"]==8]
condition_df.head()

,DUPERSID,CONDIDX,EVNTIDX,CLNKIDX,EVENTYPE,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
2,2790002101,2790002101001,2790002101002303,27900021010012790002101002303,8,E11,55.0,TYPE 2 DIABETES MELLITUS,1.0
6,2790002101,2790002101005,2790002101006400,27900021010052790002101006403,8,NaN,NaN,NaN,NaN
7,2790002101,2790002101005,2790002101007403,27900021010052790002101007403,8,NaN,NaN,NaN,NaN
8,2790002101,2790002101006,2790002101008403,27900021010062790002101008403,8,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
9,2790002101,2790002101006,2790002101008503,27900021010062790002101008503,8,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0

In [173]:
merged_df = pd.merge(clean_df, condition_df, left_on="LINKIDX", right_on="EVNTIDX", how="left")
merged_df.head()

,DUPERSID_x,DRUGIDX,LINKIDX,RXRECIDX,RXDAYSUP,RXNAME,RXBEGYRX,RXNDC,RXXP23X,RXSF23X,TC1,TC1S1,DUPERSID_y,CONDIDX,EVNTIDX,CLNKIDX,EVENTYPE,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
0,2790002101,2790002101006,2790002101006403,2790002101006403001,16,PREDNISONE,2023,591544210,7.20,7.20,97,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2790002101,2790002101007,2790002101007403,2790002101007403001,5,PREDNISONE,2023,70954006020,13.32,2.39,97,98,2.790002e+09,2.790002e+12,2.790002e+15,27900021010052790002101007403,8.0,NaN,NaN,NaN,NaN
2,2790002101,2790002101008,2790002101008403,2790002101008403001,30,METFORMIN,2020,70010006305,6.22,6.22,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008403,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
3,2790002101,2790002101008,2790002101008403,2790002101008403002,30,METFORMIN,2020,378718505,6.22,6.22,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008403,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
4,2790002101,2790002101008,2790002101008503,2790002101008503001,30,METFORMIN,2020,68645058259,4.00,4.00,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0

In [174]:
merged_df.dropna(subset = ["is_chronic"],inplace=True)
merged_df.head()

,DUPERSID_x,DRUGIDX,LINKIDX,RXRECIDX,RXDAYSUP,RXNAME,RXBEGYRX,RXNDC,RXXP23X,RXSF23X,TC1,TC1S1,DUPERSID_y,CONDIDX,EVNTIDX,CLNKIDX,EVENTYPE,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
2,2790002101,2790002101008,2790002101008403,2790002101008403001,30,METFORMIN,2020,70010006305,6.22,6.22,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008403,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
3,2790002101,2790002101008,2790002101008403,2790002101008403002,30,METFORMIN,2020,378718505,6.22,6.22,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008403,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
4,2790002101,2790002101008,2790002101008503,2790002101008503001,30,METFORMIN,2020,68645058259,4.00,4.00,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
5,2790002101,2790002101008,2790002101008503,2790002101008503002,30,METFORMIN,2020,68645058259,4.00,0.00,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
6,2790002101,2790002101008,2790002101008503,2790002101008503003,30,METFORMIN,2020,68645058259,4.00,0.00,358,99,2.790002e+09,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0

In [175]:
merged_df.drop(columns=["DUPERSID_y"],inplace=True)
merged_df.rename(columns={"DUPERSID_x":"DUPERSID"},inplace=True)
merged_df = merged_df[merged_df["RXBEGYRX"]>0]
merged_df = merged_df[merged_df["RXBEGYRX"]<=2023]
merged_df = merged_df[merged_df["RXDAYSUP"]>0]
merged_df = merged_df[merged_df["RXDAYSUP"]<990]

merged_df.head()

,DUPERSID,DRUGIDX,LINKIDX,RXRECIDX,RXDAYSUP,RXNAME,RXBEGYRX,RXNDC,RXXP23X,RXSF23X,TC1,TC1S1,CONDIDX,EVNTIDX,CLNKIDX,EVENTYPE,ICD10CDX,AGEDIAG,ICD10CDX_LABEL,is_chronic
2,2790002101,2790002101008,2790002101008403,2790002101008403001,30,METFORMIN,2020,70010006305,6.22,6.22,358,99,2.790002e+12,2.790002e+15,27900021010062790002101008403,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
3,2790002101,2790002101008,2790002101008403,2790002101008403002,30,METFORMIN,2020,378718505,6.22,6.22,358,99,2.790002e+12,2.790002e+15,27900021010062790002101008403,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
4,2790002101,2790002101008,2790002101008503,2790002101008503001,30,METFORMIN,2020,68645058259,4.00,4.00,358,99,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
5,2790002101,2790002101008,2790002101008503,2790002101008503002,30,METFORMIN,2020,68645058259,4.00,0.00,358,99,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0
6,2790002101,2790002101008,2790002101008503,2790002101008503003,30,METFORMIN,2020,68645058259,4.00,0.00,358,99,2.790002e+12,2.790002e+15,27900021010062790002101008503,8.0,E11,-1.0,TYPE 2 DIABETES MELLITUS,1.0

In [176]:
merged_df.to_excel("/Users/friana/Medical Adherence/data/MEPS/patient_conditions_df.xlsx")

In [177]:
merged_df.columns.to_list()

['DUPERSID',
 'DRUGIDX',
 'LINKIDX',
 'RXRECIDX',
 'RXDAYSUP',
 'RXNAME',
 'RXBEGYRX',
 'RXNDC',
 'RXXP23X',
 'RXSF23X',
 'TC1',
 'TC1S1',
 'CONDIDX',
 'EVNTIDX',
 'CLNKIDX',
 'EVENTYPE',
 'ICD10CDX',
 'AGEDIAG',
 'ICD10CDX_LABEL',
 'is_chronic']

In [178]:
grouped_merge_df=merged_df.groupby(["DUPERSID","DRUGIDX"]).agg(
    RXDAYSUP = ("RXDAYSUP", "sum"),
    RXXP23X = ("RXXP23X", "mean"),
    RXSF23X = ("RXSF23X", "mean"),
    RXNAME = ("RXNAME", "first"),
    RXNDC = ("RXNDC", "first"),
    RXBEGYRX = ("RXBEGYRX", "first"),
    TC1 = ("TC1", "first"),
    TC1S1 = ("TC1S1", "first"),
    ICD10CDX = ("ICD10CDX", "first"),
    ICD10CDX_LABEL = ("ICD10CDX_LABEL", "first")
    

)
grouped_merge_df.head()

                          RXDAYSUP  RXXP23X  RXSF23X        RXNAME  \
DUPERSID   DRUGIDX
2790002101 2790002101008       150    4.888    3.288     METFORMIN
2790011101 2790011101001       270   10.000   10.000   PRAVASTATIN
           2790011101002       180    8.420    3.630    AMLODIPINE
2790011102 2790011102002       180   16.900    3.000  LOSARTAN POT
           2790011102007        30    5.620    2.330  ATORVASTATIN

                                RXNDC  RXBEGYRX  TC1  TC1S1 ICD10CDX  \
DUPERSID   DRUGIDX
2790002101 2790002101008  70010006305      2020  358     99      E11
2790011101 2790011101001     93720298      2021  358     19      E78
           2790011101002  68180072003      2022   40     48      I10
2790011102 2790011102002  65862020299      2021   40     56      I10
           2790011102007  43598083005      2023  358     19      E78

                                                             ICD10CDX_LABEL
DUPERSID   DRUGIDX
2790002101 2790002101008                           TYPE 2 DIABETES MELLITUS
2790011101 2790011101001  DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...
           2790011101002                   ESSENTIAL (PRIMARY) HYPERTENSION
2790011102 2790011102002                   ESSENTIAL (PRIMARY) HYPERTENSION
           2790011102007  DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...

In [179]:
grouped_merge_df["total_valid_days"] = np.minimum(grouped_merge_df["RXDAYSUP"], 365).astype(int)

In [182]:
grouped_merge_df["total_days_supply"] = np.where(grouped_merge_df["RXBEGYRX"] <=2023, 365,0).astype(int)

In [183]:
grouped_merge_df["meps_adherence_ratio"] = grouped_merge_df["total_valid_days"]/grouped_merge_df["total_days_supply"] *100
grouped_merge_df.head()

                          RXDAYSUP  RXXP23X  RXSF23X        RXNAME  \
DUPERSID   DRUGIDX
2790002101 2790002101008       150    4.888    3.288     METFORMIN
2790011101 2790011101001       270   10.000   10.000   PRAVASTATIN
           2790011101002       180    8.420    3.630    AMLODIPINE
2790011102 2790011102002       180   16.900    3.000  LOSARTAN POT
           2790011102007        30    5.620    2.330  ATORVASTATIN

                                RXNDC  RXBEGYRX  TC1  TC1S1 ICD10CDX  \
DUPERSID   DRUGIDX
2790002101 2790002101008  70010006305      2020  358     99      E11
2790011101 2790011101001     93720298      2021  358     19      E78
           2790011101002  68180072003      2022   40     48      I10
2790011102 2790011102002  65862020299      2021   40     56      I10
           2790011102007  43598083005      2023  358     19      E78

                                                             ICD10CDX_LABEL  \
DUPERSID   DRUGIDX
2790002101 2790002101008                           TYPE 2 DIABETES MELLITUS
2790011101 2790011101001  DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...
           2790011101002                   ESSENTIAL (PRIMARY) HYPERTENSION
2790011102 2790011102002                   ESSENTIAL (PRIMARY) HYPERTENSION
           2790011102007  DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...

                          total_valid_days  total_days_supply  \
DUPERSID   DRUGIDX
2790002101 2790002101008               150                365
2790011101 2790011101001               270                365
           2790011101002               180                365
2790011102 2790011102002               180                365
           2790011102007                30                365

                          meps_adherence_ratio
DUPERSID   DRUGIDX
2790002101 2790002101008             41.095890
2790011101 2790011101001             73.972603
           2790011101002             49.315068
2790011102 2790011102002             49.315068
           2790011102007              8.219178

In [184]:
grouped_merge_df["meps_adherence_ratio"].describe()

count    21685.000000
mean        51.452017
std         33.759284
min          0.273973
25%         24.657534
50%         49.315068
75%         82.191781
max        100.000000
Name: meps_adherence_ratio, dtype: float64

In [188]:
patient_adherence = (
    grouped_merge_df.reset_index()
    .query("total_days_supply > 0")
    .groupby("DUPERSID", as_index=False)
    .agg(
        total_valid_days=("total_valid_days", "sum"),
        total_days_supply=("total_days_supply", "sum"),
        drug_count=("DRUGIDX", "count"),
    )
)
patient_adherence["meps_adherence_ratio"] = (
    patient_adherence["total_valid_days"] / patient_adherence["total_days_supply"] * 100
)

top_10_high = patient_adherence.nlargest(10, "meps_adherence_ratio")
top_10_low = patient_adherence.nsmallest(10, "meps_adherence_ratio")

output_dir = "/Users/friana/Medical Adherence/data/MEPS"
top_10_high.to_excel(f"{output_dir}/top_10_high.xlsx", index=False)
top_10_low.to_excel(f"{output_dir}/top_10_low.xlsx", index=False)

print("Top 10 patients with highest adherence:")
display(top_10_high)

print("Top 10 patients with lowest adherence:")
display(top_10_low)

Top 10 patients with highest adherence:

,DUPERSID,total_valid_days,total_days_supply,drug_count,meps_adherence_ratio
42,2790152107,365,365,1,100.0
59,2790212101,730,730,2,100.0
64,2790234101,730,730,2,100.0
65,2790234102,365,365,1,100.0
68,2790241102,1095,1095,3,100.0
146,2790501102,365,365,1,100.0
154,2790551101,365,365,1,100.0
192,2790702101,365,365,1,100.0
198,2790718101,1095,1095,3,100.0
213,2790758101,365,365,1,100.0

Top 10 patients with lowest adherence:

,DUPERSID,total_valid_days,total_days_supply,drug_count,meps_adherence_ratio
316,2791094101,1,365,1,0.273973
559,2791862101,1,365,1,0.273973
3063,2810218101,1,365,1,0.273973
3450,2811117101,1,365,1,0.273973
4384,2813661102,1,365,1,0.273973
6412,2818704101,1,365,1,0.273973
332,2791143102,2,365,1,0.547945
987,2793255102,2,365,1,0.547945
1614,2795311101,2,365,1,0.547945
2145,2796996102,2,365,1,0.547945

In [190]:
patient_drug_df = (
    grouped_merge_df.reset_index()
    .query("total_days_supply > 0")
)

top_10_high = patient_drug_df.nlargest(10, "meps_adherence_ratio")
top_10_low = patient_drug_df.nsmallest(10, "meps_adherence_ratio")

output_dir = "/Users/friana/Medical Adherence/data/MEPS"
top_10_high.to_excel(f"{output_dir}/top_10_high.xlsx", index=False)
top_10_low.to_excel(f"{output_dir}/top_10_low.xlsx", index=False)

print("Top 10 patient-drug pairs with highest adherence:")
display(top_10_high)

print("Top 10 patient-drug pairs with lowest adherence:")
display(top_10_low)

Top 10 patient-drug pairs with highest adherence:

,DUPERSID,DRUGIDX,RXDAYSUP,RXXP23X,RXSF23X,RXNAME,RXNDC,RXBEGYRX,TC1,TC1S1,ICD10CDX,ICD10CDX_LABEL,total_valid_days,total_days_supply,meps_adherence_ratio
50,2790067101,2790067101003,450,3.310000,0.000,ATENOLOL,93078701,2005,40,47,I10,ESSENTIAL (PRIMARY) HYPERTENSION,365,365,100.0
51,2790067101,2790067101006,460,1.460000,0.000,LOSARTAN POT,43547036009,2005,40,56,E78,DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...,365,365,100.0
92,2790119102,2790119102004,450,23.460000,11.356,TRAZODONE,50111056101,2019,242,249,G47,SLEEP DISORDERS,365,365,100.0
104,2790150101,2790150101001,450,517.030000,192.375,LUMIGAN,23320505,2020,133,147,H40,GLAUCOMA,365,365,100.0
105,2790150101,2790150101002,800,4.100000,4.100,TIMOLOL MAL,61314022710,2020,133,147,H40,GLAUCOMA,365,365,100.0
111,2790152107,2790152107002,810,5.590000,5.590,ATORVASTATIN,378395177,2015,358,19,E78,DISORDERS OF LIPOPROTEIN METABOLISM AND OTHER ...,365,365,100.0
113,2790161101,2790161101006,380,10.555000,0.000,LISINOPRIL,68645055354,2000,40,42,I10,ESSENTIAL (PRIMARY) HYPERTENSION,365,365,100.0
129,2790172102,2790172102016,450,9.600000,2.904,METFORMIN,68645058259,2023,358,99,E11,TYPE 2 DIABETES MELLITUS,365,365,100.0
187,2790210104,2790210104005,540,53.394000,0.000,SERTRALINE,68180035309,2012,242,249,J30,VASOMOTOR AND ALLERGIC RHINITIS,365,365,100.0
194,2790210104,2790210104014,660,12.212727,0.000,FLUTICASONE,60505082901,2018,133,247,J30,VASOMOTOR AND ALLERGIC RHINITIS,365,365,100.0

Top 10 patient-drug pairs with lowest adherence:

,DUPERSID,DRUGIDX,RXDAYSUP,RXXP23X,RXSF23X,RXNAME,RXNDC,RXBEGYRX,TC1,TC1S1,ICD10CDX,ICD10CDX_LABEL,total_valid_days,total_days_supply,meps_adherence_ratio
1039,2791094101,2791094101006,1,15.00,15.00,LATANOPROST,59762033302,2023,133,147,H40,GLAUCOMA,1,365,0.273973
1863,2791862101,2791862101008,1,199.22,178.14,CLENPIQ,55566670001,2023,87,95,K59,OTHER FUNCTIONAL INTESTINAL DISORDERS,1,365,0.273973
2613,2792644101,2792644101015,1,0.13,0.13,LORAZEPAM,69315090405,2023,57,64,F41,OTHER ANXIETY DISORDERS,1,365,0.273973
6566,2796548101,2796548101007,1,0.50,0.50,DIAZEPAM,172392670,2023,57,64,F41,OTHER ANXIETY DISORDERS,1,365,0.273973
7720,2797673101,2797673101009,1,0.14,0.14,PREDNISONE,70954006020,2023,97,98,J30,VASOMOTOR AND ALLERGIC RHINITIS,1,365,0.273973
8317,2798198101,2798198101007,1,22.65,10.00,GAVILYTE-G,43386009019,2023,87,95,K57,DIVERTICULAR DISEASE OF INTESTINE,1,365,0.273973
9840,2810147101,2810147101001,1,12.31,12.31,DIAZEPAM,172392760,2023,57,64,F41,OTHER ANXIETY DISORDERS,1,365,0.273973
9925,2810218101,2810218101001,1,0.13,0.13,LORAZEPAM,69315090405,2023,57,64,F41,OTHER ANXIETY DISORDERS,1,365,0.273973
10341,2810550101,2810550101012,1,0.78,0.00,AMOXICILLIN,781261305,2023,1,13,J32,CHRONIC SINUSITIS,1,365,0.273973
11116,2811117101,2811117101004,1,0.13,0.13,LORAZEPAM,69315090405,2017,57,64,F41,OTHER ANXIETY DISORDERS,1,365,0.273973

In [ ]:
adherence_threshold = 60

In [193]:
print(grouped_merge_df["ICD10CDX"].nunique())
print(grouped_merge_df["TC1"].nunique())
print(grouped_merge_df["RXNAME"].nunique())

74
17
757

In [ ]:
grouped_merge_df.to_excel("/Users/friana/Medical Adherence/data/MEPS/grouped_merge_df.xlsx")