In [15]:
from pathlib import Path

import pandas as pd

TABLES_DIR = Path("output/all_years/tables")

model_df = pd.read_parquet(TABLES_DIR / "model_df_all_years.parquet")
model_df_pair = pd.read_parquet(TABLES_DIR / "model_df_pair_all_years.parquet")

print("model_df_all_years shape:", model_df.shape)
print("columns:", list(model_df.columns))
display(model_df.head())

print("\nmodel_df_pair_all_years shape:", model_df_pair.shape)
print("columns:", list(model_df_pair.columns))
display(model_df_pair.head())

model_df_all_years shape: (28691, 328)
columns: ['DUPERSID', 'YEAR', 'AGE', 'FAMINC', 'is_adherent', 'INSCOV_PRIVATE', 'INSCOV_PUBLIC', 'INSCOV_UNINSURED', 'MALE', 'FEMALE', 'WHITE', 'BLACK', 'AMER_INDIAN', 'ASIAN_INDIAN', 'CHINESE', 'FILIPINO', 'PMED_DELAY_COST', 'NO_PMED_DELAY_COST', 'CARE_DELAY_COST', 'NO_CARE_DELAY_COST', 'POV_POOR', 'POV_NEAR_POOR', 'POV_LOW', 'POV_MIDDLE', 'POV_HIGH', 'RXDRG_5-AMINOSALICYLATES', 'RXDRG_ACE INHIBITORS WITH THIAZIDES', 'RXDRG_ADALIMUMAB', 'RXDRG_ALENDRONATE', 'RXDRG_ALLOPURINOL', 'RXDRG_AMIODARONE', 'RXDRG_AMITRIPTYLINE', 'RXDRG_AMLODIPINE', 'RXDRG_AMLODIPINE-BENAZEPRIL', 'RXDRG_AMPHETAMINE-DEXTROAMPHETAMINE', 'RXDRG_ANASTROZOLE', 'RXDRG_ANGIOTENSIN CONVERTING ENZYME (ACE) INHIBITORS', 'RXDRG_ANGIOTENSIN II INHIBITORS', 'RXDRG_ANGIOTENSIN II INHIBITORS WITH THIAZIDES', 'RXDRG_ANTICHOLINERGICS/ANTISPASMODICS', 'RXDRG_ANTICONVULSANTS', 'RXDRG_ANTIDIABETIC AGENTS', 'RXDRG_ANTIHYPERLIPIDEMIC AGENTS', 'RXDRG_ANTIHYPERTENSIVE COMBINATIONS', 'RXDRG_ANTINEOPLASTIC HORMONES', 'RXDRG_APIXABAN', 'RXDRG_ARIPIPRAZOLE', 'RXDRG_ASPIRIN', 'RXDRG_ATENOLOL', 'RXDRG_ATOMOXETINE', 'RXDRG_ATORVASTATIN', 'RXDRG_AZELAIC ACID TOPICAL', 'RXDRG_BACLOFEN', 'RXDRG_BARBITURATE ANTICONVULSANTS', 'RXDRG_BENAZEPRIL', 'RXDRG_BENZODIAZEPINE ANTICONVULSANTS', 'RXDRG_BIMATOPROST OPHTHALMIC', 'RXDRG_BISOPROLOL', 'RXDRG_BISPHOSPHONATES', 'RXDRG_BRIMONIDINE OPHTHALMIC', 'RXDRG_BUDESONIDE', 'RXDRG_BUDESONIDE NASAL', 'RXDRG_BUDESONIDE-FORMOTEROL', 'RXDRG_BUMETANIDE', 'RXDRG_BUPROPION', 'RXDRG_BUSPIRONE', 'RXDRG_CALCITRIOL', 'RXDRG_CALCIUM ACETATE', 'RXDRG_CARBAMAZEPINE', 'RXDRG_CARBIDOPA-LEVODOPA', 'RXDRG_CARBONIC ANHYDRASE INHIBITORS', 'RXDRG_CARVEDILOL', 'RXDRG_CHLORTHALIDONE', 'RXDRG_CHOLINESTERASE INHIBITORS', 'RXDRG_CITALOPRAM', 'RXDRG_CLONIDINE', 'RXDRG_CLOPIDOGREL', 'RXDRG_CNS STIMULANTS', 'RXDRG_CYCLOSPORINE OPHTHALMIC', 'RXDRG_DAPAGLIFLOZIN', 'RXDRG_DESVENLAFAXINE', 'RXDRG_DEXMETHYLPHENIDATE', 'RXDRG_DICYCLOMINE', 'RXDRG_DILTIAZEM', 'RXDRG_DIURETICS', 'RXDRG_DIVALPROEX SODIUM', 'RXDRG_DONEPEZIL', 'RXDRG_DOPAMINERGIC ANTIPARKINSONISM AGENTS', 'RXDRG_DORZOLAMIDE OPHTHALMIC', 'RXDRG_DORZOLAMIDE-TIMOLOL OPHTHALMIC', 'RXDRG_DOXAZOSIN', 'RXDRG_DOXEPIN', 'RXDRG_DULAGLUTIDE', 'RXDRG_DULOXETINE', 'RXDRG_EMPAGLIFLOZIN', 'RXDRG_EMTRICITABINE-TENOFOVIR', 'RXDRG_ENALAPRIL', 'RXDRG_ESCITALOPRAM', 'RXDRG_ESTRADIOL', 'RXDRG_ESTRADIOL TOPICAL', 'RXDRG_EVOLOCUMAB', 'RXDRG_EZETIMIBE', 'RXDRG_FENOFIBRATE', 'RXDRG_FINASTERIDE', 'RXDRG_FLECAINIDE', 'RXDRG_FLUOXETINE', 'RXDRG_FLUTICASONE', 'RXDRG_FLUTICASONE NASAL', 'RXDRG_FLUTICASONE-SALMETEROL', 'RXDRG_FLUTICASONE-VILANTEROL', 'RXDRG_FLUTICASONE/UMECLIDINIUM/VILANTEROL', 'RXDRG_FUNCTIONAL BOWEL DISORDER AGENTS', 'RXDRG_FUROSEMIDE', 'RXDRG_GABAPENTIN', 'RXDRG_GLIMEPIRIDE', 'RXDRG_GLIPIZIDE', 'RXDRG_GROUP II ANTIARRHYTHMICS', 'RXDRG_GROUP III ANTIARRHYTHMICS', 'RXDRG_GUANFACINE', 'RXDRG_HYDRALAZINE', 'RXDRG_HYDROCHLOROTHIAZIDE', 'RXDRG_HYDROCHLOROTHIAZIDE-LISINOPRIL', 'RXDRG_HYDROCHLOROTHIAZIDE-LOSARTAN', 'RXDRG_HYDROCHLOROTHIAZIDE-TRIAMTERENE', 'RXDRG_HYDROXYCHLOROQUINE', 'RXDRG_ICOSAPENT', 'RXDRG_INHALED CORTICOSTEROIDS', 'RXDRG_INSULIN', 'RXDRG_INSULIN ASPART', 'RXDRG_INSULIN DEGLUDEC', 'RXDRG_INSULIN DETEMIR', 'RXDRG_INSULIN GLARGINE', 'RXDRG_INSULIN ISOPHANE-INSULIN REGULAR', 'RXDRG_INSULIN LISPRO', 'RXDRG_IRBESARTAN', 'RXDRG_ISOSORBIDE MONONITRATE', 'RXDRG_LABETALOL', 'RXDRG_LAMOTRIGINE', 'RXDRG_LATANOPROST OPHTHALMIC', 'RXDRG_LEVETIRACETAM', 'RXDRG_LEVOTHYROXINE', 'RXDRG_LINACLOTIDE', 'RXDRG_LINAGLIPTIN', 'RXDRG_LIOTHYRONINE', 'RXDRG_LIRAGLUTIDE', 'RXDRG_LISDEXAMFETAMINE', 'RXDRG_LISINOPRIL', 'RXDRG_LITHIUM', 'RXDRG_LOSARTAN', 'RXDRG_LOVASTATIN', 'RXDRG_MEMANTINE', 'RXDRG_MESALAMINE', 'RXDRG_METFORMIN', 'RXDRG_METHIMAZOLE', 'RXDRG_METHOTREXATE', 'RXDRG_METHYLPHENIDATE', 'RXDRG_METOPROLOL', 'RXDRG_MIRABEGRON', 'RXDRG_MIRTAZAPINE', 'RXDRG_MISCELLANEOUS CARDIOVASCULAR AGENTS', 'RXDRG_MONTELUKAST', 'RXDRG_MORPHINE', 'RXDRG_NEBIVOLOL', 'RXDRG_NIACIN', 'RXDRG_NIFEDIPINE', 'RXDRG_NITROGLYCERIN', 'RXDRG_NORTRIPTYLINE', 'RXDRG_OLANZAPINE', 'RXDRG_OLMESARTAN', 'RXDRG_OXCARBAZEPINE', 'RXDRG_OXYBUTYNIN', 'RXDRG_OXYCODONE', 'RXDRG_PANCRELIPASE', 'RXDRG_PAROXETINE', 'RXDRG_PIOGLITAZONE', 'RXDRG_PLATELET AGGREGATION INHIBITORS', 'RXDRG_POTASSIUM CHLORIDE', 'RXDRG_PRAMIPEXOLE', 'RXDRG_PRAVASTATIN', 'RXDRG_PREGABALIN', 'RXDRG_PRIMIDONE', 'RXDRG_PROGESTERONE', 'RXDRG_PROPRANOLOL', 'RXDRG_QUETIAPINE', 'RXDRG_RAMIPRIL', 'RXDRG_RISPERIDONE', 'RXDRG_RIVAROXABAN', 'RXDRG_ROPINIROLE', 'RXDRG_ROSUVASTATIN', 'RXDRG_SACUBITRIL-VALSARTAN', 'RXDRG_SEMAGLUTIDE', 'RXDRG_SERTRALINE', 'RXDRG_SEX HORMONES', 'RXDRG_SIMVASTATIN', 'RXDRG_SITAGLIPTIN', 'RXDRG_SODIUM BICARBONATE', 'RXDRG_SOLIFENACIN', 'RXDRG_SPIRONOLACTONE', 'RXDRG_SULFACETAMIDE SODIUM-SULFUR TOPICAL', 'RXDRG_TAMSULOSIN', 'RXDRG_TELMISARTAN', 'RXDRG_TERAZOSIN', 'RXDRG_TESTOSTERONE', 'RXDRG_THIAZIDE AND THIAZIDE-LIKE DIURETICS', 'RXDRG_THYROID DESICCATED', 'RXDRG_TICAGRELOR', 'RXDRG_TIMOLOL OPHTHALMIC', 'RXDRG_TIOTROPIUM', 'RXDRG_TOPIRAMATE', 'RXDRG_TORSEMIDE', 'RXDRG_TRAZODONE', 'RXDRG_TRICYCLIC ANTIDEPRESSANTS', 'RXDRG_URINARY ANTISPASMODICS', 'RXDRG_VALSARTAN', 'RXDRG_VENLAFAXINE', 'RXDRG_VERAPAMIL', 'RXDRG_WARFARIN', 'ICD_C18', 'ICD_C34', 'ICD_C43', 'ICD_C44', 'ICD_C50', 'ICD_C61', 'ICD_C67', 'ICD_C73', 'ICD_C95', 'ICD_E03', 'ICD_E05', 'ICD_E11', 'ICD_E28', 'ICD_E29', 'ICD_E34', 'ICD_E78', 'ICD_F03', 'ICD_F20', 'ICD_F31', 'ICD_F32', 'ICD_F39', 'ICD_F41', 'ICD_F84', 'ICD_F90', 'ICD_F99', 'ICD_G20', 'ICD_G25', 'ICD_G40', 'ICD_G47', 'ICD_G62', 'ICD_H35', 'ICD_H40', 'ICD_H54', 'ICD_I10', 'ICD_I20', 'ICD_I25', 'ICD_I48', 'ICD_I49', 'ICD_I50', 'ICD_I51', 'ICD_J30', 'ICD_J32', 'ICD_J42', 'ICD_J43', 'ICD_J44', 'ICD_J45', 'ICD_K21', 'ICD_K50', 'ICD_K57', 'ICD_K58', 'ICD_K59', 'ICD_K76', 'ICD_M06', 'ICD_M10', 'ICD_M17', 'ICD_M19', 'ICD_M35', 'ICD_M48', 'ICD_M50', 'ICD_M51', 'ICD_M53', 'ICD_M54', 'ICD_M81', 'ICD_M85', 'ICD_N18', 'ICD_N19', 'ICD_N40', 'ICD_R26', 'ICD_R32', 'ICD_R54', 'ICD_Z79', 'meps_adherence_ratio', 'PATIENT_COST_SHARE', 'n_drugs', 'n_conditions', 'RXDRG_ALBUTEROL', 'RXDRG_ATYPICAL ANTIPSYCHOTICS', 'RXDRG_BETA BLOCKERS, NON-CARDIOSELECTIVE', 'RXDRG_ESTROGENS', 'RXDRG_GROUP I ANTIARRHYTHMICS', 'RXDRG_HMG-COA REDUCTASE INHIBITORS (STATINS)', 'RXDRG_MISCELLANEOUS ANTINEOPLASTICS', 'RXDRG_MTOR INHIBITORS', 'RXDRG_MULTIVITAMIN WITH MINERALS', 'RXDRG_OPHTHALMIC GLAUCOMA AGENTS', 'RXDRG_SGLT-2 INHIBITORS', 'RXDRG_SSRI ANTIDEPRESSANTS', 'RXDRG_VASODILATORS', 'ICD_F19', 'ICD_M72', 'RXDRG_ALPHA-ADRENORECEPTOR ANTAGONISTS', 'RXDRG_CHOLINERGIC AGONISTS', 'RXDRG_GLP-1 RECEPTOR AGONISTS', 'RXDRG_GROUP V ANTIARRHYTHMICS', 'RXDRG_ANTIANGINAL AGENTS', 'RXDRG_CGRP INHIBITORS', 'RXDRG_CROMOLYN OPHTHALMIC', 'RXDRG_DOCUSATE-SENNA', 'RXDRG_DUTASTERIDE', 'RXDRG_FIBRIC ACID DERIVATIVES', 'RXDRG_TIRZEPATIDE', 'ICD_U09', 'MARRYXX', 'REGIONXX', 'EDUCYR', 'RACETHX', 'medication_freq', 'medication_dose', 'medication_dose_unit', 'medication_qty_unit', 'medication_freq_bin']

,DUPERSID,YEAR,AGE,FAMINC,is_adherent,INSCOV_PRIVATE,INSCOV_PUBLIC,INSCOV_UNINSURED,MALE,FEMALE,...,ICD_U09,MARRYXX,REGIONXX,EDUCYR,RACETHX,medication_freq,medication_dose,medication_dose_unit,medication_qty_unit,medication_freq_bin
0,2320005102,2020,84,17000,1,0,1,0,1,0,...,0,1,1,12,2,1.333333,34.166667,MG,TABS,2x_daily
1,2320013101,2020,85,18960,0,0,1,0,0,1,...,0,5,3,6,1,1.183333,34.500500,MG,TABS,1x_daily
2,2320018101,2020,58,28920,1,0,1,0,0,1,...,0,1,4,12,2,1.333333,30.000000,MG,TABS,2x_daily
3,2320018102,2020,72,28920,1,0,1,0,1,0,...,0,1,4,12,2,1.303571,57.628571,MCG/ACT,AERS,2x_daily
4,2320019102,2020,47,98788,1,1,0,0,0,1,...,0,1,4,12,2,1.000000,100.000000,MCG,TABS,1x_daily

model_df_pair_all_years shape: (79029, 39)
columns: ['DUPERSID', 'DRUGIDX', 'RXDRGNAME', 'ICD10CDX', 'AGE', 'FAMINC', 'RXSF_PATIENT', 'RXXP_TOTAL', 'meps_adherence_ratio', 'total_days_supply', 'drug_start_days', 'RXBEGYRX', 'first_month', 'chronic_conditions', 'n_chronic_conditions', 'TC1', 'TC1S1', 'YEAR', 'is_adherent', 'INSCOV_PRIVATE', 'INSCOV_PUBLIC', 'INSCOV_UNINSURED', 'MALE', 'FEMALE', 'WHITE', 'BLACK', 'AMER_INDIAN', 'ASIAN_INDIAN', 'CHINESE', 'FILIPINO', 'PMED_DELAY_COST', 'NO_PMED_DELAY_COST', 'CARE_DELAY_COST', 'NO_CARE_DELAY_COST', 'POV_POOR', 'POV_NEAR_POOR', 'POV_LOW', 'POV_MIDDLE', 'POV_HIGH']

,DUPERSID,DRUGIDX,RXDRGNAME,ICD10CDX,AGE,FAMINC,RXSF_PATIENT,RXXP_TOTAL,meps_adherence_ratio,total_days_supply,...,FILIPINO,PMED_DELAY_COST,NO_PMED_DELAY_COST,CARE_DELAY_COST,NO_CARE_DELAY_COST,POV_POOR,POV_NEAR_POOR,POV_LOW,POV_MIDDLE,POV_HIGH
0,2320005102,2320005102001,LOSARTAN,I10,84,17000,10.596667,113.010000,73.972603,365,...,0,0,1,0,1,0,1,0,0,0
1,2320005102,2320005102002,HYDROCHLOROTHIAZIDE,I10,84,17000,3.000000,22.456667,73.972603,365,...,0,0,1,0,1,0,1,0,0,0
2,2320013101,2320013101002,LATANOPROST OPHTHALMIC,H40,85,18960,1.300000,23.750000,61.643836,365,...,0,0,1,0,1,0,0,1,0,0
3,2320013101,2320013101008,ATORVASTATIN,E78,85,18960,0.000000,3.120000,16.438356,365,...,0,0,1,0,1,0,0,1,0,0
4,2320013101,2320013101011,MIRTAZAPINE,G47,85,18960,0.000000,9.000000,24.657534,365,...,0,0,1,0,1,0,0,1,0,0

In [16]:
# Column names only (exclude RXDRG_* and ICD_* dummies)
model_df_cols = [
    c for c in model_df.columns
    if not str(c).startswith(("RXDRG_", "ICD_"))
]

cols_path = TABLES_DIR / "model_df_all_years_columns.csv"
pd.DataFrame({"column": model_df_cols}).to_csv(cols_path, index=False)

print(f"Wrote {len(model_df_cols)} columns -> {cols_path}")
model_df_cols

Wrote 38 columns -> output/all_years/tables/model_df_all_years_columns.csv

['DUPERSID',
 'YEAR',
 'AGE',
 'FAMINC',
 'is_adherent',
 'INSCOV_PRIVATE',
 'INSCOV_PUBLIC',
 'INSCOV_UNINSURED',
 'MALE',
 'FEMALE',
 'WHITE',
 'BLACK',
 'AMER_INDIAN',
 'ASIAN_INDIAN',
 'CHINESE',
 'FILIPINO',
 'PMED_DELAY_COST',
 'NO_PMED_DELAY_COST',
 'CARE_DELAY_COST',
 'NO_CARE_DELAY_COST',
 'POV_POOR',
 'POV_NEAR_POOR',
 'POV_LOW',
 'POV_MIDDLE',
 'POV_HIGH',
 'meps_adherence_ratio',
 'PATIENT_COST_SHARE',
 'n_drugs',
 'n_conditions',
 'MARRYXX',
 'REGIONXX',
 'EDUCYR',
 'RACETHX',
 'medication_freq',
 'medication_dose',
 'medication_dose_unit',
 'medication_qty_unit',
 'medication_freq_bin']

In [17]:
import numpy as np

# --- Labels ---
POV_LABELS = {
    "POV_POOR": "Poor",
    "POV_NEAR_POOR": "Near poor",
    "POV_LOW": "Low income",
    "POV_MIDDLE": "Middle income",
    "POV_HIGH": "High income",
}
INSCOV_LABELS = {
    "INSCOV_PRIVATE": "Private",
    "INSCOV_PUBLIC": "Public",
    "INSCOV_UNINSURED": "Uninsured",
}
MARRY_LABELS = {
    1: "Married",
    2: "Widowed",
    3: "Divorced",
    4: "Separated",
    5: "Never married",
    6: "Under 16",
    -7: "Inapplicable / DK",
}
REGION_LABELS = {1: "Northeast", 2: "Midwest", 3: "South", 4: "West"}
OUTCOME_LABELS = {True: "Became adherent (≥60%)", False: "Stayed <60%"}

COVARIATE_COLS = [
    "AGE",
    "FAMINC",
    "meps_adherence_ratio",
    "PATIENT_COST_SHARE",
    "n_drugs",
    "n_conditions",
    "MARRYXX",
    "REGIONXX",
    "EDUCYR",
    "medication_freq",
    "medication_dose",
    "medication_freq_bin",
    *POV_LABELS.keys(),
    *INSCOV_LABELS.keys(),
]


def _one_hot_label(row, mapping):
    for col, label in mapping.items():
        if row.get(col, 0) == 1:
            return label
    return "Unknown"


def summarize_change_vs_outcome(df, change_col, title):
    """Rate of becoming adherent by a YoY change category."""
    tab = (
        df.groupby(change_col, dropna=False, observed=False)
        .agg(
            n_people=("DUPERSID", "size"),
            n_became_adherent=("became_adherent", "sum"),
            mean_adh_change=("adh_change", "mean"),
        )
        .reset_index()
    )
    tab["pct_became_adherent"] = (
        tab["n_became_adherent"] / tab["n_people"].replace(0, np.nan) * 100
    ).round(1)
    tab["mean_adh_change"] = tab["mean_adh_change"].round(1)
    tab = tab.rename(
        columns={
            change_col: "Change",
            "n_people": "N (person-years)",
            "n_became_adherent": "Became adherent",
            "mean_adh_change": "Mean adherence Δ (pp)",
            "pct_became_adherent": "% became adherent",
        }
    )
    print(title)
    display(tab)
    return tab


# --- Build consecutive-year person pairs with covariates ---
base = model_df[["DUPERSID", "YEAR", *COVARIATE_COLS]].copy()
base["AGE"] = pd.to_numeric(base["AGE"], errors="coerce")

prev = base.rename(columns={c: f"{c}_prev" for c in ["YEAR", *COVARIATE_COLS]})
nxt = base.rename(columns={c: f"{c}_next" for c in ["YEAR", *COVARIATE_COLS]})
year_pairs = prev.merge(nxt, on="DUPERSID")
year_pairs = year_pairs[year_pairs["YEAR_next"] == year_pairs["YEAR_prev"] + 1].copy()

year_pairs["prior_adherence_pct"] = np.floor(year_pairs["meps_adherence_ratio_prev"]).astype(int)
year_pairs["adh_change"] = (
    year_pairs["meps_adherence_ratio_next"] - year_pairs["meps_adherence_ratio_prev"]
)
year_pairs["became_adherent"] = year_pairs["meps_adherence_ratio_next"] >= 60
year_pairs["outcome"] = year_pairs["became_adherent"].map(OUTCOME_LABELS)

year_pairs["pov_prev"] = year_pairs.apply(
    lambda r: _one_hot_label(r, {f"{k}_prev": v for k, v in POV_LABELS.items()}), axis=1
)
year_pairs["pov_next"] = year_pairs.apply(
    lambda r: _one_hot_label(r, {f"{k}_next": v for k, v in POV_LABELS.items()}), axis=1
)
year_pairs["inscov_prev"] = year_pairs.apply(
    lambda r: _one_hot_label(r, {f"{k}_prev": v for k, v in INSCOV_LABELS.items()}), axis=1
)
year_pairs["inscov_next"] = year_pairs.apply(
    lambda r: _one_hot_label(r, {f"{k}_next": v for k, v in INSCOV_LABELS.items()}), axis=1
)
year_pairs["marry_prev"] = year_pairs["MARRYXX_prev"].map(MARRY_LABELS).fillna("Other")
year_pairs["marry_next"] = year_pairs["MARRYXX_next"].map(MARRY_LABELS).fillna("Other")
year_pairs["region_prev"] = year_pairs["REGIONXX_prev"].map(REGION_LABELS).fillna("Other")
year_pairs["region_next"] = year_pairs["REGIONXX_next"].map(REGION_LABELS).fillna("Other")

# Cohort: prior-year adherence 50–59%
near_miss = year_pairs[
    (year_pairs["prior_adherence_pct"] >= 50) & (year_pairs["prior_adherence_pct"] <= 59)
].copy()

became_adherent_by_pct = (
    pd.DataFrame({"Prior-year adherence": [f"{p}%" for p in range(50, 60)]})
    .assign(prior_adherence_pct=range(50, 60))
    .merge(
        near_miss.loc[near_miss["became_adherent"]]
        .groupby("prior_adherence_pct", as_index=False)
        .agg(**{"Became adherent next year": ("DUPERSID", "nunique")}),
        on="prior_adherence_pct",
        how="left",
    )
    .merge(
        near_miss.groupby("prior_adherence_pct", as_index=False).agg(
            **{"People at this prior %": ("DUPERSID", "nunique")}
        ),
        on="prior_adherence_pct",
        how="left",
    )
    .fillna(0)
)
became_adherent_by_pct["Became adherent next year"] = became_adherent_by_pct[
    "Became adherent next year"
].astype(int)
became_adherent_by_pct["People at this prior %"] = became_adherent_by_pct[
    "People at this prior %"
].astype(int)
became_adherent_by_pct["% who became adherent"] = (
    became_adherent_by_pct["Became adherent next year"]
    / became_adherent_by_pct["People at this prior %"].replace(0, np.nan)
    * 100
).round(1)
became_adherent_by_pct = became_adherent_by_pct.drop(columns=["prior_adherence_pct"])

print(
    f"Consecutive person-year pairs: {len(year_pairs):,}\n"
    f"Prior year 50–59%: {near_miss['DUPERSID'].nunique():,} people "
    f"({len(near_miss):,} transitions)\n"
    f"Became adherent (≥60%) next year: "
    f"{near_miss.loc[near_miss['became_adherent'], 'DUPERSID'].nunique():,} people "
    f"({100 * near_miss['became_adherent'].mean():.1f}% of near-miss transitions)"
)
display(became_adherent_by_pct)
print("Total became adherent:", int(became_adherent_by_pct["Became adherent next year"].sum()))
print(
    "\nLater cells compare covariate changes among this 50–59% → next-year cohort "
    "(became adherent vs stayed <60%)."
)

Consecutive person-year pairs: 9,919
Prior year 50–59%: 935 people (963 transitions)
Became adherent (≥60%) next year: 446 people (46.3% of near-miss transitions)

,Prior-year adherence,Became adherent next year,People at this prior %,% who became adherent
0,50%,22,43,51.2
1,51%,20,56,35.7
2,52%,47,90,52.2
3,53%,49,108,45.4
4,54%,43,115,37.4
5,55%,44,95,46.3
6,56%,35,66,53.0
7,57%,106,221,48.0
8,58%,47,94,50.0
9,59%,33,71,46.5

Total became adherent: 446

Later cells compare covariate changes among this 50–59% → next-year cohort (became adherent vs stayed <60%).

## Covariate changes vs becoming adherent

Cohort = prior-year adherence **50–59%**, with a consecutive next-year observation.  
Outcome = next-year adherence **≥ 60%** vs stayed **&lt; 60%**.

In [18]:
# Income bracket (POV) — did poverty category change?
near_miss["income_change"] = np.where(
    near_miss["pov_prev"] == near_miss["pov_next"],
    "Same income bracket",
    near_miss["pov_prev"] + " → " + near_miss["pov_next"],
)
_pov_order = ["Poor", "Near poor", "Low income", "Middle income", "High income"]
_pov_rank = {v: i for i, v in enumerate(_pov_order)}
_prev_r = near_miss["pov_prev"].map(_pov_rank)
_next_r = near_miss["pov_next"].map(_pov_rank)
near_miss["income_direction"] = np.select(
    [
        _prev_r.isna() | _next_r.isna(),
        _next_r > _prev_r,
        _next_r < _prev_r,
        _next_r == _prev_r,
    ],
    ["Unknown", "Moved up", "Moved down", "No change"],
    default="Unknown",
)

_income_dir = summarize_change_vs_outcome(
    near_miss,
    "income_direction",
    "Income (POV): direction of poverty-bracket change vs becoming adherent",
)
print("\nDetail: specific bracket transitions (top by n)")
_detail = summarize_change_vs_outcome(
    near_miss, "income_change", "Income (POV): specific bracket transitions"
).sort_values("N (person-years)", ascending=False)
display(_detail.head(15))

Income (POV): direction of poverty-bracket change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Moved down,231,102,2.1,44.2
1,Moved up,164,63,-0.3,38.4
2,No change,568,281,3.8,49.5

Detail: specific bracket transitions (top by n)
Income (POV): specific bracket transitions

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,High income → Low income,7,3,10.1,42.9
1,High income → Middle income,84,36,1.2,42.9
2,High income → Near poor,2,0,-7.9,0.0
3,High income → Poor,11,3,-4.7,27.3
4,Low income → High income,11,3,-6.1,27.3
5,Low income → Middle income,38,17,0.5,44.7
6,Low income → Near poor,17,6,-0.3,35.3
7,Low income → Poor,33,17,1.5,51.5
8,Middle income → High income,38,13,-5.6,34.2
9,Middle income → Low income,35,17,5.3,48.6
10,Middle income → Near poor,5,3,2.7,60.0
11,Middle income → Poor,19,9,7.2,47.4
12,Near poor → Low income,13,7,14.8,53.8
13,Near poor → Middle income,5,2,1.6,40.0
14,Near poor → Poor,18,8,0.3,44.4
15,Poor → High income,11,5,5.4,45.5
16,Poor → Low income,27,8,-1.6,29.6
17,Poor → Middle income,11,6,10.5,54.5
18,Poor → Near poor,10,2,-11.6,20.0
19,Same income bracket,568,281,3.8,49.5

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
19,Same income bracket,568,281,3.8,49.5
1,High income → Middle income,84,36,1.2,42.9
5,Low income → Middle income,38,17,0.5,44.7
8,Middle income → High income,38,13,-5.6,34.2
9,Middle income → Low income,35,17,5.3,48.6
7,Low income → Poor,33,17,1.5,51.5
16,Poor → Low income,27,8,-1.6,29.6
11,Middle income → Poor,19,9,7.2,47.4
14,Near poor → Poor,18,8,0.3,44.4
6,Low income → Near poor,17,6,-0.3,35.3
12,Near poor → Low income,13,7,14.8,53.8
3,High income → Poor,11,3,-4.7,27.3
4,Low income → High income,11,3,-6.1,27.3
17,Poor → Middle income,11,6,10.5,54.5
15,Poor → High income,11,5,5.4,45.5

In [19]:
# Insurance (INSCOV) — did coverage type change?
near_miss["insurance_change"] = np.where(
    near_miss["inscov_prev"] == near_miss["inscov_next"],
    "Same: " + near_miss["inscov_prev"],
    near_miss["inscov_prev"] + " → " + near_miss["inscov_next"],
)
near_miss["insurance_direction"] = np.select(
    [
        near_miss["inscov_prev"] == near_miss["inscov_next"],
        (near_miss["inscov_prev"] == "Uninsured")
        & (near_miss["inscov_next"] != "Uninsured"),
        (near_miss["inscov_prev"] != "Uninsured")
        & (near_miss["inscov_next"] == "Uninsured"),
    ],
    ["No change", "Gained coverage", "Lost coverage"],
    default="Switched coverage type",
)

summarize_change_vs_outcome(
    near_miss,
    "insurance_direction",
    "Insurance (INSCOV): coverage change vs becoming adherent",
)
print("\nDetail: specific insurance transitions")
summarize_change_vs_outcome(
    near_miss, "insurance_change", "Insurance (INSCOV): specific transitions"
)

Insurance (INSCOV): coverage change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Gained coverage,9,3,5.8,33.3
1,Lost coverage,2,1,9.1,50.0
2,No change,894,414,2.6,46.3
3,Switched coverage type,58,28,4.1,48.3

Detail: specific insurance transitions
Insurance (INSCOV): specific transitions

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Private → Public,29,16,8.6,55.2
1,Private → Uninsured,2,1,9.1,50.0
2,Public → Private,29,12,-0.5,41.4
3,Same: Private,462,214,2.2,46.3
4,Same: Public,419,196,3.1,46.8
5,Same: Uninsured,13,4,-2.5,30.8
6,Uninsured → Private,3,1,7.3,33.3
7,Uninsured → Public,6,2,5.1,33.3

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Private → Public,29,16,8.6,55.2
1,Private → Uninsured,2,1,9.1,50.0
2,Public → Private,29,12,-0.5,41.4
3,Same: Private,462,214,2.2,46.3
4,Same: Public,419,196,3.1,46.8
5,Same: Uninsured,13,4,-2.5,30.8
6,Uninsured → Private,3,1,7.3,33.3
7,Uninsured → Public,6,2,5.1,33.3

In [20]:
# Patient cost share — did out-of-pocket medication share change?
near_miss["cost_share_change"] = (
    near_miss["PATIENT_COST_SHARE_next"] - near_miss["PATIENT_COST_SHARE_prev"]
)
near_miss["cost_share_direction"] = pd.cut(
    near_miss["cost_share_change"],
    bins=[-np.inf, -0.05, 0.05, np.inf],
    labels=["Decreased (>5 pp)", "Little/no change (±5 pp)", "Increased (>5 pp)"],
)

summarize_change_vs_outcome(
    near_miss,
    "cost_share_direction",
    "Patient cost share: OOP medication share change vs becoming adherent",
)

print("\nMean cost-share change by outcome")
display(
    near_miss.groupby("outcome")
    .agg(
        n=("DUPERSID", "size"),
        mean_cost_share_prev=("PATIENT_COST_SHARE_prev", "mean"),
        mean_cost_share_next=("PATIENT_COST_SHARE_next", "mean"),
        mean_cost_share_change=("cost_share_change", "mean"),
    )
    .round(3)
)

Patient cost share: OOP medication share change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Decreased (>5 pp),292,129,2.8,44.2
1,Little/no change (±5 pp),406,200,3.5,49.3
2,Increased (>5 pp),265,117,1.3,44.2

Mean cost-share change by outcome

,n,mean_cost_share_prev,mean_cost_share_next,mean_cost_share_change
outcome,,,,
Became adherent (≥60%),446,0.342,0.325,-0.017
Stayed <60%,517,0.334,0.321,-0.012

In [21]:
# Education (EDUCYR) — did years of education go up?
# MEPS EDUCYR can include special codes; treat only sensible 0–17 year values.
_ed_prev = near_miss["EDUCYR_prev"].where(
    near_miss["EDUCYR_prev"].between(0, 17)
)
_ed_next = near_miss["EDUCYR_next"].where(
    near_miss["EDUCYR_next"].between(0, 17)
)
near_miss["educ_change"] = _ed_next - _ed_prev
near_miss["educ_direction"] = np.select(
    [
        near_miss["educ_change"].isna(),
        near_miss["educ_change"] > 0,
        near_miss["educ_change"] < 0,
        near_miss["educ_change"] == 0,
    ],
    ["Unknown / invalid", "Increased", "Decreased", "No change"],
    default="Unknown / invalid",
)

summarize_change_vs_outcome(
    near_miss,
    "educ_direction",
    "Education (EDUCYR): change in years of education vs becoming adherent",
)

print("\nMean education years by outcome")
display(
    near_miss.groupby("outcome")
    .agg(
        n=("DUPERSID", "size"),
        mean_educ_prev=("EDUCYR_prev", "mean"),
        mean_educ_next=("EDUCYR_next", "mean"),
        mean_educ_change=("educ_change", "mean"),
    )
    .round(2)
)

Education (EDUCYR): change in years of education vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,No change,961,445,2.7,46.3
1,Unknown / invalid,2,1,20.5,50.0

Mean education years by outcome

                          n  mean_educ_prev  mean_educ_next  mean_educ_change
outcome
Became adherent (≥60%)  446           12.79           12.79               0.0
Stayed <60%             517           12.97           12.97               0.0

In [22]:
# Marital status (MARRYXX) — did it change?
near_miss["marry_change"] = np.where(
    near_miss["marry_prev"] == near_miss["marry_next"],
    "Same: " + near_miss["marry_prev"],
    near_miss["marry_prev"] + " → " + near_miss["marry_next"],
)
near_miss["marry_direction"] = np.where(
    near_miss["MARRYXX_prev"] == near_miss["MARRYXX_next"],
    "No change",
    "Changed",
)

summarize_change_vs_outcome(
    near_miss,
    "marry_direction",
    "Marital status (MARRYXX): any change vs becoming adherent",
)
print("\nDetail: specific marital transitions (n ≥ 5)")
_m = summarize_change_vs_outcome(
    near_miss, "marry_change", "Marital status (MARRYXX): specific transitions"
)
display(_m.loc[_m["N (person-years)"] >= 5].sort_values("N (person-years)", ascending=False))

Marital status (MARRYXX): any change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Changed,24,11,1.7,45.8
1,No change,939,435,2.7,46.3

Detail: specific marital transitions (n ≥ 5)
Marital status (MARRYXX): specific transitions

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Divorced → Married,4,1,-4.3,25.0
1,Divorced → Widowed,1,0,-23.8,0.0
2,Married → Divorced,2,2,25.7,100.0
3,Married → Widowed,6,2,1.9,33.3
4,Never married → Married,2,2,9.5,100.0
5,Same: Divorced,203,96,3.4,47.3
6,Same: Married,436,198,2.3,45.4
7,Same: Never married,131,62,2.9,47.3
8,Same: Separated,19,10,3.0,52.6
9,Same: Under 16,18,11,3.1,61.1
10,Same: Widowed,132,58,2.9,43.9
11,Separated → Divorced,5,2,-4.0,40.0
12,Under 16 → Never married,2,1,9.2,50.0
13,Widowed → Married,2,1,0.4,50.0

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
6,Same: Married,436,198,2.3,45.4
5,Same: Divorced,203,96,3.4,47.3
10,Same: Widowed,132,58,2.9,43.9
7,Same: Never married,131,62,2.9,47.3
8,Same: Separated,19,10,3.0,52.6
9,Same: Under 16,18,11,3.1,61.1
3,Married → Widowed,6,2,1.9,33.3
11,Separated → Divorced,5,2,-4.0,40.0

In [23]:
# Region (REGIONXX) — did census region change?
near_miss["region_change"] = np.where(
    near_miss["region_prev"] == near_miss["region_next"],
    "Same: " + near_miss["region_prev"],
    near_miss["region_prev"] + " → " + near_miss["region_next"],
)
near_miss["region_direction"] = np.where(
    near_miss["REGIONXX_prev"] == near_miss["REGIONXX_next"],
    "No change",
    "Moved region",
)

summarize_change_vs_outcome(
    near_miss,
    "region_direction",
    "Region (REGIONXX): move vs becoming adherent",
)
print("\nDetail: by region / move")
summarize_change_vs_outcome(
    near_miss, "region_change", "Region (REGIONXX): specific region transitions"
)

Region (REGIONXX): move vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Moved region,7,2,-5.0,28.6
1,No change,956,444,2.8,46.4

Detail: by region / move
Region (REGIONXX): specific region transitions

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Midwest → South,1,0,-17.8,0.0
1,Midwest → West,3,1,-0.4,33.3
2,Northeast → South,1,0,-7.2,0.0
3,Same: Midwest,208,107,4.6,51.4
4,Same: Northeast,154,74,5.2,48.1
5,Same: South,350,149,0.9,42.6
6,Same: West,244,114,2.2,46.7
7,South → Northeast,1,0,-40.8,0.0
8,West → Midwest,1,1,31.5,100.0

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Midwest → South,1,0,-17.8,0.0
1,Midwest → West,3,1,-0.4,33.3
2,Northeast → South,1,0,-7.2,0.0
3,Same: Midwest,208,107,4.6,51.4
4,Same: Northeast,154,74,5.2,48.1
5,Same: South,350,149,0.9,42.6
6,Same: West,244,114,2.2,46.7
7,South → Northeast,1,0,-40.8,0.0
8,West → Midwest,1,1,31.5,100.0

In [24]:
# Drugs / conditions / frequency / dose — did regimen intensity change?
near_miss["n_drugs_change"] = near_miss["n_drugs_next"] - near_miss["n_drugs_prev"]
near_miss["n_conditions_change"] = (
    near_miss["n_conditions_next"] - near_miss["n_conditions_prev"]
)
near_miss["freq_change"] = (
    near_miss["medication_freq_next"] - near_miss["medication_freq_prev"]
)
near_miss["dose_change"] = (
    near_miss["medication_dose_next"] - near_miss["medication_dose_prev"]
)

near_miss["n_drugs_direction"] = np.select(
    [
        near_miss["n_drugs_change"] > 0,
        near_miss["n_drugs_change"] < 0,
        near_miss["n_drugs_change"] == 0,
    ],
    ["More drugs", "Fewer drugs", "Same # drugs"],
    default="Unknown",
)
near_miss["n_conditions_direction"] = np.select(
    [
        near_miss["n_conditions_change"] > 0,
        near_miss["n_conditions_change"] < 0,
        near_miss["n_conditions_change"] == 0,
    ],
    ["More conditions", "Fewer conditions", "Same # conditions"],
    default="Unknown",
)
near_miss["freq_direction"] = np.select(
    [
        near_miss["freq_change"] > 0.1,
        near_miss["freq_change"] < -0.1,
    ],
    ["Frequency up", "Frequency down"],
    default="Frequency ~same",
)
near_miss["dose_direction"] = np.select(
    [
        near_miss["dose_change"] > 0,
        near_miss["dose_change"] < 0,
    ],
    ["Dose up", "Dose down"],
    default="Dose same",
)
near_miss["freq_bin_change"] = np.where(
    near_miss["medication_freq_bin_prev"] == near_miss["medication_freq_bin_next"],
    "Same bin: " + near_miss["medication_freq_bin_prev"].astype(str),
    near_miss["medication_freq_bin_prev"].astype(str)
    + " → "
    + near_miss["medication_freq_bin_next"].astype(str),
)

summarize_change_vs_outcome(
    near_miss, "n_drugs_direction", "Number of drugs: change vs becoming adherent"
)
summarize_change_vs_outcome(
    near_miss,
    "n_conditions_direction",
    "Number of conditions: change vs becoming adherent",
)
summarize_change_vs_outcome(
    near_miss, "freq_direction", "Medication frequency: change vs becoming adherent"
)
summarize_change_vs_outcome(
    near_miss, "dose_direction", "Medication dose: change vs becoming adherent"
)

print("\nMean regimen deltas by outcome")
display(
    near_miss.groupby("outcome")
    .agg(
        n=("DUPERSID", "size"),
        mean_delta_drugs=("n_drugs_change", "mean"),
        mean_delta_conditions=("n_conditions_change", "mean"),
        mean_delta_freq=("freq_change", "mean"),
        mean_delta_dose=("dose_change", "mean"),
    )
    .round(2)
)

print("\nFrequency bin transitions")
summarize_change_vs_outcome(
    near_miss, "freq_bin_change", "Medication frequency bin transitions"
)

Number of drugs: change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Fewer drugs,299,118,-0.7,39.5
1,More drugs,286,137,4.1,47.9
2,Same # drugs,378,191,4.3,50.5

Number of conditions: change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Fewer conditions,213,83,-1.6,39.0
1,More conditions,215,98,3.7,45.6
2,Same # conditions,535,265,4.0,49.5

Medication frequency: change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Frequency down,352,169,2.9,48.0
1,Frequency up,375,167,2.3,44.5
2,Frequency ~same,236,110,2.9,46.6

Medication dose: change vs becoming adherent

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,Dose down,449,215,3.2,47.9
1,Dose same,82,49,9.6,59.8
2,Dose up,432,182,0.8,42.1

Mean regimen deltas by outcome

,n,mean_delta_drugs,mean_delta_conditions,mean_delta_freq,mean_delta_dose
outcome,,,,,
Became adherent (≥60%),446,0.13,0.04,0.02,-41.94
Stayed <60%,517,-0.17,-0.05,0.05,-44.76

Frequency bin transitions
Medication frequency bin transitions

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,1x_daily → 2x_daily,134,62,3.1,46.3
1,1x_daily → 3x_daily,11,4,-6.4,36.4
2,1x_daily → 4x_plus,7,4,3.7,57.1
3,2x_daily → 1x_daily,129,71,3.9,55.0
4,2x_daily → 3x_daily,27,11,3.4,40.7
5,2x_daily → 4x_plus,3,2,11.2,66.7
6,3x_daily → 1x_daily,11,4,-5.8,36.4
7,3x_daily → 2x_daily,24,10,1.4,41.7
8,3x_daily → 4x_plus,2,0,-19.0,0.0
9,4x_plus → 2x_daily,3,3,21.9,100.0
10,Same bin: 1x_daily,246,113,3.2,45.9
11,Same bin: 2x_daily,348,158,2.8,45.4
12,Same bin: 3x_daily,15,4,-10.3,26.7
13,Same bin: 4x_plus,3,0,-2.8,0.0

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,1x_daily → 2x_daily,134,62,3.1,46.3
1,1x_daily → 3x_daily,11,4,-6.4,36.4
2,1x_daily → 4x_plus,7,4,3.7,57.1
3,2x_daily → 1x_daily,129,71,3.9,55.0
4,2x_daily → 3x_daily,27,11,3.4,40.7
5,2x_daily → 4x_plus,3,2,11.2,66.7
6,3x_daily → 1x_daily,11,4,-5.8,36.4
7,3x_daily → 2x_daily,24,10,1.4,41.7
8,3x_daily → 4x_plus,2,0,-19.0,0.0
9,4x_plus → 2x_daily,3,3,21.9,100.0
10,Same bin: 1x_daily,246,113,3.2,45.9
11,Same bin: 2x_daily,348,158,2.8,45.4
12,Same bin: 3x_daily,15,4,-10.3,26.7
13,Same bin: 4x_plus,3,0,-2.8,0.0

In [25]:
# Age — does getting older (or age group) relate to becoming adherent?
near_miss["age_change"] = near_miss["AGE_next"] - near_miss["AGE_prev"]
near_miss["age_group_prev"] = pd.cut(
    near_miss["AGE_prev"],
    bins=[0, 39, 49, 64, 74, 120],
    labels=["18–39", "40–49", "50–64", "65–74", "75+"],
    right=True,
)

summarize_change_vs_outcome(
    near_miss,
    "age_group_prev",
    "Age group (prior year): who becomes adherent next year?",
)

print("\nMean age / age change by outcome")
display(
    near_miss.groupby("outcome")
    .agg(
        n=("DUPERSID", "size"),
        mean_age_prev=("AGE_prev", "mean"),
        mean_age_next=("AGE_next", "mean"),
        mean_age_change=("age_change", "mean"),
        pct_became=("became_adherent", "mean"),
    )
    .assign(pct_became=lambda d: (d["pct_became"] * 100).round(1))
    .round(2)
)

print("\nBecame-adherent rate by prior age group (same as first table, labeled)")
_age_tab = (
    near_miss.groupby("age_group_prev", observed=True)
    .agg(
        n_people=("DUPERSID", "size"),
        n_became_adherent=("became_adherent", "sum"),
        mean_adh_change=("adh_change", "mean"),
        mean_age=("AGE_prev", "mean"),
    )
    .reset_index()
)
_age_tab["pct_became_adherent"] = (
    _age_tab["n_became_adherent"] / _age_tab["n_people"] * 100
).round(1)
_age_tab["mean_adh_change"] = _age_tab["mean_adh_change"].round(1)
_age_tab["mean_age"] = _age_tab["mean_age"].round(1)
display(_age_tab)

Age group (prior year): who becomes adherent next year?

,Change,N (person-years),Became adherent,Mean adherence Δ (pp),% became adherent
0,18–39,98,47,1.7,48.0
1,40–49,98,46,2.8,46.9
2,50–64,312,137,0.2,43.9
3,65–74,264,119,3.3,45.1
4,75+,191,97,6.3,50.8

Mean age / age change by outcome

,n,mean_age_prev,mean_age_next,mean_age_change,pct_became
outcome,,,,,
Became adherent (≥60%),446,61.1,62.06,0.97,100.0
Stayed <60%,517,60.97,61.95,0.98,0.0

Became-adherent rate by prior age group (same as first table, labeled)

,age_group_prev,n_people,n_became_adherent,mean_adh_change,mean_age,pct_became_adherent
0,18–39,98,47,1.7,27.4,48.0
1,40–49,98,46,2.8,45.4,46.9
2,50–64,312,137,0.2,57.7,43.9
3,65–74,264,119,3.3,69.5,45.1
4,75+,191,97,6.3,80.0,50.8